// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/sweetheart0330/metrics-alert/internal/model"
	observer "github.com/sweetheart0330/metrics-alert/internal/observer"
	"go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockObserver) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockObserverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObserver)(nil).Close))
}

// Consume mocks base method.
func (m *MockObserver) Consume(ctx context.Context, ev models.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockObserverMockRecorder) Consume(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockObserver)(nil).Consume), ctx, ev)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// NotifyObservers mocks base method.
func (m *MockPublisher) NotifyObservers(ctx context.Context, ev models.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyObservers", ctx, ev)
}

// NotifyObservers indicates an expected call of NotifyObservers.
func (mr *MockPublisherMockRecorder) NotifyObservers(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyObservers", reflect.TypeOf((*MockPublisher)(nil).NotifyObservers), ctx, ev)
}

// Register mocks base method.
func (m *MockPublisher) Register(o observer.Observer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", o)
}

// Register indicates an expected call of Register.
func (mr *MockPublisherMockRecorder) Register(o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockPublisher)(nil).Register), o)
}
